//
//  Constants.swift
//  MyMood
//
//  Created by Glauber Gustavo on 30/03/23.
//

class Constants {
    
    struct API {
        static let authToken: String = ""
    }
    
    struct Messages {
        static let Empty = ""
        static let And = " e "
        static let Comma = ", "
        static let Name = "Nome: "
        static let textConcatenation = "(?<=Nome: ).*$"
        static let Recipe = "Receita"
        static let Thanks = "Obrigado!"
        static let SeeDataMood = "Veja seus dados do humor"
        static let Exit = "Sair"
        static let Warning = "Atenção!"
        static let ChooseIngredients = "Você precisa escolher pelo menos 3 ingredientes para poder gerar sua receita!"
        static let Ok = "OK"
        static let prompt = "Faça uma receita, contendo quantidades de ingredientes e o modo de preparo, com os seguintes ingredientes e depois dê um nome pra ela (descricão do nome vem depois da palavra 'Nome:'): "
        static let ReadyRecipe = "Ready_Recipe"
        static let Banana = "Banana"
        static let Onion = "Cebola"
        static let Sugar = "Açúcar"
        static let Meat = "Carne"
        static let Rice = "Arroz"
        static let Bean = "Feijão"
        static let Cheese = "Queijo"
        static let Eggs = "Ovos"
        static let Tomato = "Tomate"
        static let Chicken = "Frango"
        static let Noodle = "Macarrão"
        static let Potato = "Batata"
        static let Yam = "Inhame"
        static let Lettuce = "Alface"
        static let CreamyCheese = "Requeijão"
        static let Carrot = "Cenoura"
        static let Flour = "Farinha"
        static let Butter = "Manteiga"
        static let Coriander = "Coentro"
        static let MaizeStarch = "Amido de milho"
        static let TomatoExtract = "Extrato de tomate"
        static let Honey = "Mel"
        static let Chocolate = "Chocolate"
        static let SweetenedCondensedMilk = "Leite Condensado"
        static let Bacon = "Bacon"
        static let OliveOil = "Azeite"
        static let Sausage = "Salsicha"
        static let Parsley = "Salsinha"
        static let Cookies = "Biscoitos"
        static let Strawberry = "Morangos"
        static let CookingOil = "Óleo de cozinha"
        static let Lemon = "Limão"
        static let Ferment = "Fermento"
        static let CornFlakes = "Flocos de milho"
        static let Cassava = "Mandioca"
        static let Coconut = "Côco"
        static let CocoMilk = "Leite de côco"
        static let Corn = "Milho"
        static let Peas = "Ervilhas"
        static let Lentil = "Lentilha"
        static let CassavaGum = "Goma de mandioca"
        static let Pumpkin = "Abóbora"
        static let SweetPotato = "Batata doce"
        static let Tuna = "Atum"
        static let Mushrooms = "Cogumelos"
        static let Shrimp = "Camarão"
        static let Sardine = "Sardinha"
        static let Chayote = "Chuchu"
    }
    
    struct Images {
        static let LeftButton = "left207"
        static let iconCheckGreen = "icon_check_green"
        
        static let Banana = "Banana"
        static let Onion = "Onion"
        static let Sugar = "Sugar"
        static let Meat = "Meat"
        static let Rice = "Rice"
        static let Bean = "Bean"
        static let Cheese = "Cheese"
        static let Eggs = "Eggs"
        static let Tomato = "Tomato"
        static let Chicken = "Chicken"
        static let Noodle = "Noodle"
        static let Potato = "Potato"
        static let Yam = "Yam"
        static let Lettuce = "Lettuce"
        static let CreamyCheese = "Cream_Cheese"
        static let Carrot = "Carrot"
        static let Flour = "Flour"
        static let Butter = "Butter"
        static let Coriander = "Coriander"
        static let MaizeStarch = "Maize_Starch"
        static let TomatoExtract = "Tomato_Extract"
        static let Honey = "Honey"
        static let Chocolate = "Chocolate"
        static let SweetenedCondensedMilk = "Sweetened_Condensed_Milk"
        static let Bacon = "Bacon"
        static let OliveOil = "Olive_Oil"
        static let Sausage = "Sausage"
        static let Parsley = "Parsley"
        static let Cookies = "Cookies"
        static let Strawberry = "Strawberry"
        static let CookingOil = "Cooking_Oil"
        static let Lemon = "Lemon"
        static let Ferment = "Ferment"
        static let CornFlakes = "Corn_Flakes"
        static let Cassava = "Cassava"
        static let Coconut = "Coconut"
        static let CocoMilk = "Coco_Milk"
        static let Corn = "Corn"
        static let Peas = "Peas"
        static let Lentil = "Lentil"
        static let CassavaGum = "Cassava_Gum"
        static let Pumpkin = "Pumpkin"
        static let SweetPotato = "Sweet_Potato"
        static let Tuna = "Tuna"
        static let Mushrooms = "Mushrooms"
        static let Shrimp = "Shrimp"
        static let Sardine = "Sardine"
        static let Chayote = "Chayote"
    }
    
    struct Storyboards {
        static let Home = "Home"
        static let HomeView = "HomeView"
        static let Recipe = "Recipe"
        static let RecipeView = "RecipeView"
    }
    
    struct Fonts {
        static let RobotoBold = "Roboto-Bold"
    }
}
